/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentRoles;

import Business.Enterprise.Enterprise;
import Business.Organization.GovernmentHeadOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestGovernmentRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumedhtelang
 */
public class GovernmentHeadOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentHeadOfficerWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private GovernmentHeadOrganization governmentHeadOrganization;
    private Enterprise enterprise;
    public GovernmentHeadOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.governmentHeadOrganization = (GovernmentHeadOrganization)governmentHeadOrganization;
        this.enterprise = enterprise;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblProcess.getModel();
        model.setRowCount(0);

        for (WorkRequest request : governmentHeadOrganization.getWorkQueue().getWorkRequestList()) {
            String status = request.getCurrentStatus();
            Object[] row = new Object[6];
            row[0] = request.getProvider().getEmployee().getName();
            if (status.equalsIgnoreCase("Sent") || status.equalsIgnoreCase("Sent")) {
                row[1] = null;
            } else {
                row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            }
            //row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[2] = status;
            row[3] = ((RequestGovernmentRequest) request).getRequestAmount();
            row[4] = ((RequestGovernmentRequest) request).getMessage();
            row[5] = request;

            model.addRow(row);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcess = new javax.swing.JTable();
        processRequestBtn = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        tblProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Funds/Foods", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProcess);
        if (tblProcess.getColumnModel().getColumnCount() > 0) {
            tblProcess.getColumnModel().getColumn(0).setResizable(false);
            tblProcess.getColumnModel().getColumn(1).setResizable(false);
            tblProcess.getColumnModel().getColumn(2).setResizable(false);
            tblProcess.getColumnModel().getColumn(3).setResizable(false);
            tblProcess.getColumnModel().getColumn(4).setResizable(false);
            tblProcess.getColumnModel().getColumn(5).setResizable(false);
        }

        processRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-process-32.png"))); // NOI18N
        processRequestBtn.setText("Process");
        processRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestBtnActionPerformed(evt);
            }
        });

        btnAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-audit-32.png"))); // NOI18N
        btnAssign.setText("Assign To Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(processRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(processRequestBtn))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProcess.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details", "Warning!", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            RequestGovernmentRequest request = (RequestGovernmentRequest) tblProcess.getValueAt(selectedRow, 5);
            if (request.getCurrentStatus().equalsIgnoreCase("Sent to Treasurer")) {
                JOptionPane.showMessageDialog(null, "Please assign selected request first");
                return;
            }
            if (request.getCurrentStatus().equalsIgnoreCase("Accepted")) {
                JOptionPane.showMessageDialog(null, "Request already completed");
                return;
            }
            if(!userAccount.equals(request.getReceiver())){
             JOptionPane.showMessageDialog(null, "Not Authorized");
                return;
            }
            if (!userAccount.getEmployee().equals(request.getReceiver().getEmployee())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getCurrentStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            //request.setStatus("Processing");
            HeadRequestJPanel treasurerProcessWorkRequestJPanel = new HeadRequestJPanel(userProcessContainer, request);
            userProcessContainer.add("TreasurerProcessWorkRequestJPanel", treasurerProcessWorkRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_processRequestBtnActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProcess.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details", "Warning!", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            WorkRequest request = (RequestGovernmentRequest) tblProcess.getValueAt(selectedRow, 5);
            if (request.getCurrentStatus().equals("Sent to Treasurer")) {
                request.setReceiver(userAccount);
                request.setCurrentStatus("Pending on " + request.getReceiver().getEmployee().getName());
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + request.getCurrentStatus() + " status");
            }
        }
        
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processRequestBtn;
    private javax.swing.JTable tblProcess;
    // End of variables declaration//GEN-END:variables
}
