/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.Enterprise.Enterprise;
import Business.Organization.FoodDistributionOrganization;
import Business.Organization.GoodsSupplierOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.WorkQueue.SupervisorWorkRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author sumedhtelang
 */
public class ProcessSupervisorRequest extends javax.swing.JPanel {

    /**
     * Creates new form ProcessSupervisorRequest
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private FoodDistributionOrganization foodDistributionOrganization;
    private GoodsSupplierOrganization goodsSupplierOrganization;

    public ProcessSupervisorRequest(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, FoodDistributionOrganization foodDistributionOrganization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.foodDistributionOrganization = foodDistributionOrganization;
        
        valueLbl.setText(enterprise.getEnterpriseName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageTxtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();
        approvalRequestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        messageTxtArea.setColumns(20);
        messageTxtArea.setRows(5);
        jScrollPane1.setViewportView(messageTxtArea);

        jLabel1.setText("Message For Supervisor :");

        jLabel2.setText("Enterprise :");

        valueLbl.setText("<value>");

        approvalRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-approval-50.png"))); // NOI18N
        approvalRequestBtn.setText("Request Approval");
        approvalRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvalRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(approvalRequestBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueLbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valueLbl))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(approvalRequestBtn)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approvalRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvalRequestBtnActionPerformed
        // TODO add your handling code here:
        String message = messageTxtArea.getText();
        SupervisorWorkRequest request = new SupervisorWorkRequest();
        request.setMessage(message);
        if(request.getMessage().isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter a Message!!");        
        }
        else{
                request.setReceiver(userAccount);
                request.setCurrentStatus("Sent");
            }
        Organization org = null;
        for (Organization organisation : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organisation instanceof GoodsSupplierOrganization){
                org = organisation;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            //goodsSupplierOrganization = (GoodsSupplierOrganization)org;
            //goodsSupplierOrganization.getApprovalQueue().add(request);
            //foodDistributionOrganization.getReplyApprovalQueue().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_approvalRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvalRequestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageTxtArea;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
}
