/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentRoles;

import Business.Enterprise.Enterprise;
import Business.Organization.GovernmentHeadOrganization;
import Business.Organization.GovernmentSecretaryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestGovernmentRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sumedhtelang
 */
public class OfficerWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OfficerWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private RequestGovernmentRequest requestGovernmentRequest;
    private GovernmentOfficerWorkAreaJPanel officerWorkAreaJPanel;

    public OfficerWorkRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, RequestGovernmentRequest request, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.requestGovernmentRequest = request;
        fundsTxtField.setText(String.valueOf(requestGovernmentRequest.getRequestAmount()));
        locationTxtField.setText(requestGovernmentRequest.getLocation());
        peopleTxtField.setText(String.valueOf(requestGovernmentRequest.getPopulation()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        locationTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        peopleTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fundsTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        messageTxtField = new javax.swing.JTextField();
        sendRequestForFinalBtn = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("City");

        jLabel3.setText("Number Of People ");

        jLabel4.setText("Funds/Food");

        jLabel1.setText("Message");

        sendRequestForFinalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-submit-document-32.png"))); // NOI18N
        sendRequestForFinalBtn.setText("Send Request For Final Approval");
        sendRequestForFinalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestForFinalBtnActionPerformed(evt);
            }
        });

        btnReject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-file-delete-32.png"))); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-26.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationTxtField)
                    .addComponent(peopleTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(fundsTxtField)
                    .addComponent(messageTxtField))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendRequestForFinalBtn)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(locationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(peopleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendRequestForFinalBtn))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fundsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnReject)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GovernmentOfficerWorkAreaJPanel owjp = (GovernmentOfficerWorkAreaJPanel) component;
        owjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        String message = messageTxtField.getText();
        requestGovernmentRequest.setMessage(message);
        requestGovernmentRequest.setCurrentStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Request Rejected!");
    }//GEN-LAST:event_btnRejectActionPerformed

    private void sendRequestForFinalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestForFinalBtnActionPerformed
        // TODO add your handling code here:
        String message = messageTxtField.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        }
        requestGovernmentRequest.setMessage(message);
        requestGovernmentRequest.setProvider(userAccount);
        requestGovernmentRequest.setCurrentStatus("Approved");

//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//            if (organization instanceof GovernmentSecretaryOrganization) {
//                org = organization;
//                break;
//            }
//        }
//        if (org != null) {
//            org.getWorkQueue().getWorkRequestList().add(requestGovernmentRequest);
//            userAccount.getWorkQueue().getWorkRequestList().add(requestGovernmentRequest);
//        }
//        JOptionPane.showMessageDialog(null, "Request to Secretary Successful!!!");

    }//GEN-LAST:event_sendRequestForFinalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JTextField fundsTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField locationTxtField;
    private javax.swing.JTextField messageTxtField;
    private javax.swing.JTextField peopleTxtField;
    private javax.swing.JButton sendRequestForFinalBtn;
    // End of variables declaration//GEN-END:variables
}
