/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HomelessShelterRoles;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FoodDistributionOrganization;
import Business.Organization.HomelessShelterManagerOrganization;
import Business.Organization.HomelessShelterDonationOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeliveryStatus;
import Business.WorkQueue.QuotationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.NGORole.NGOFoodPublishWorkAreaJPanel;

/**
 *
 * @author sumedhtelang
 */
public class HomelessShelterDonationsWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomelessShelterDonationsWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private HomelessShelterDonationOrganization homelessShelterDonationOrganization;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization outorganization;
    private Network network;
    EcoSystem ecosystem;
    private TableRowSorter<DefaultTableModel> sorter;
    private WorkRequest request;
    

    public HomelessShelterDonationsWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization,
            EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.ecosystem = ecosystem;
        this.userProcessContainer = userProcessContainer;
        this.homelessShelterDonationOrganization = homelessShelterDonationOrganization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = organization;
        populateTable();
        
        
    }
    
    public void populateTable(){
        DefaultTableModel model2 = (DefaultTableModel) quotationWorkTable.getModel();
        
        model2.setRowCount(0);
        
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getRequirement();
            row[2] = request.getCurrentStatus();
            String result =  request.getDecision();
             
            model2.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        quotationWorkTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        quotationBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        quotationWorkTable.setBackground(new java.awt.Color(153, 255, 153));
        quotationWorkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name of organization", "Food Quoted", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(quotationWorkTable);
        if (quotationWorkTable.getColumnModel().getColumnCount() > 0) {
            quotationWorkTable.getColumnModel().getColumn(0).setResizable(false);
            quotationWorkTable.getColumnModel().getColumn(1).setResizable(false);
            quotationWorkTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Homeless Shelter Donations Request Panel");

        quotationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-submit-document-32.png"))); // NOI18N
        quotationBtn.setText("Send Quotation");
        quotationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quotationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quotationBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(quotationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quotationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quotationBtnActionPerformed
        // TODO add your handling code here:
        try
        {        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("quotationJPanel", new QuotationFormWorkArea(userProcessContainer, userAccount, homelessShelterDonationOrganization , enterprise));
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Invalid Opreation");

        }
    }//GEN-LAST:event_quotationBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quotationBtn;
    private javax.swing.JTable quotationWorkTable;
    // End of variables declaration//GEN-END:variables
}
